name: 'Initialize AWS and Terraform'
description: 'Composite action for automation of the AWS login and Terraform initialization.'
runs:
  using: "composite"
  steps:
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.access_key_id }}
        aws-secret-access-key: ${{ inputs.secret_access_key }}
        aws-region: ${{ inputs.default_region }}
        role-to-assume: ${{ inputs.arn_role }} 
        role-session-name: github-actions-session

    # Step 3: Set up Terraform (Install Terraform)
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    # Step 4: Terraform initialization
    - run: terraform init
      shell: bash
      working-directory: ./${{ steps.select-module.outputs.MODULE }}

    # Step 5: Terraform apply (provision resources)
    - name: Terraform apply
      run: terraform apply -auto-approve
