name: 'Initialize Azure and Terraform'
description: 'Composite action for automating the Terraform initialization process for Azure.'

inputs:
  terraform_module:
    description: "Terraform module name"
    required: true
    type: string

  azure_client_id:
    description: "Azure service principal id (client id)"
    required: true
    type: string

  azure_subscription_id:
    description: "Azure subscription id"
    required: true
    type: string

  azure_tenant_id:
    description: "Azure tenant id"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - run: terraform init
      shell: bash
      working-directory: azure/${{ inputs.terraform_module }}