name: Terraform apply reusable workflow

on:
  workflow_call:
    inputs:
      cloud-provider:
        required: true
        type: string
      module:
        required: true
        type: string

jobs:
  apply:
    name: Apply Terraform configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/
        with:
          cloud-provider: ${{ inputs.cloud-provider }}
          terraform-module: ${{ inputs.module }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-arn-role: ${{ secrets.AWS_ARN_ROLE }}
          aws-default-region: eu-central-1

      - name: Terraform apply
        working-directory: ${{ inputs.cloud-provider }}/${{ inputs.module }}
        run: |
          export ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}
          if [ "${{ inputs.cloud-provider }}" == "azure" ]; then
            terraform apply -var subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }} -auto-approve
          else
            terraform apply -auto-approve
          fi
