name: Terraform apply workflow

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    name: Apply Terraform configuration
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Azure login and Terraform initialization
        id: composite-action
        uses: ./.github/actions/terraform-tutorials/actions/

      - name: Terraform apply command
        run: terraform apply -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -input=false
        working-directory: ./${{ steps.composite-action.outputs.working-directory }}