name: Terraform apply reusable workflow

on:
  workflow_call:
    inputs:
      cloud-provider:
        required: true
        type: string
      module:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    name: Apply Terraform configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login and Terraform initialization
        if: ${{ inputs.cloud-provider == 'azure' }}
        uses: ./.github/actions/azure-actions
        with:
          terraform_module: ${{ inputs.module }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        
      - name: Azure login and Terraform initialization
        if: ${{ inputs.cloud-provider == 'aws' }}
        uses: ./.github/actions/aws-actions
        with:
          terraform_module: ${{ inputs.module }}
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          default_region: "eu-central-1"
          arn_role: ${{ secrets.AWS_ARN_ROLE }}

      - name: Terraform apply
        run: |
          if [ "${{ inputs.cloud-provider }}" == "azure" ]; then
            terraform apply -var subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }} -auto-approve
          else
            terraform apply -auto-approve
          fi
        working-directory: ./${{ inputs.module }}