name: Terraform plan reusable workflow

on:
  workflow_call:
    inputs:
      cloud-provider:
        required: true
        type: string
      module:
        required: true
        type: string

jobs:
  terraform-plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Azure login and Terraform initialization
        id: composite-action
        if: ${{ inputs.cloud-provider == 'azure' }}
        uses: ./.github/actions/azure-actions
        with:
          terraform_module: ${{ inputs.module }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Terraform plan
        run: |
          if [ "${{ inputs.cloud-provider }}" == "azure" ]; then
            terraform plan -var subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }} -out .planfile
          else
            terraform plan -out .planfile
          fi
        working-directory: ${{ inputs.cloud-provider }}/${{ inputs.module }}
      
      - name: Post PR comment
        uses: borchero/terraform-plan-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          planfile: .planfile
          working-directory: ${{ inputs.cloud-provider }}/${{ inputs.module }}
