name: Terraform apply workflow

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    name: Apply Terraform configuration
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v4

      - name: Azure login and Terraform initialization
        id: composite-action
        uses: ./.github/actions/azure-actions
        with:
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}

      - run: |
          pwd
          ls -alh
        working-directory: ./${{ steps.composite-action.outputs.working-directory }}
        
      - name: Terraform apply command
        run: terraform apply -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -input=false
        working-directory: ./${{ steps.composite-action.outputs.working-directory }}