name: Terraform plan workflow

on:
  # workflow_dispatch:
  pull_request:
    types: [opened, edited]
    branches:
      - main
  push:
    branches-ignore:
      - main

jobs:
  plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    environment:
      name: dev
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Azure login and Terraform initialization
        id: composite-action
        uses: ./.github/actions/azure-action

      - run: terraform plan -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -out .planfile
        working-directory: ./${{ steps.composite-action.outputs.working-directory }}
      
      - name: Post PR comment
        uses: borchero/terraform-plan-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          planfile: .planfile
          working-directory: ./${{ steps.composite-action.outputs.working-directory }}
