name: Terraform plan reusable workflow

on:
  workflow_call:
    inputs:
      cloud-provider:
        required: true
        type: string
      module:
        required: true
        type: string

jobs:
  terraform-plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Log into Azure regardless of the cloud provider we are provisioning on.
      # This is because the storage where we save Terraform state files is a
      # container in an Azure storage account.
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      # Without setting the following environment variables, Terraform would try
      # to build the AzureRM client by authenticating to Azure using the Azure CLI, 
      # which is only supported as a user and not as a service principal. 
      - name: Set environment variables
        # Since every step runs its own shell environment, exporting variables is not
        # sufficient to extend their scope to later steps. The way to make them available
        # is to append them to the GITHUB_OUTPUT environment variable.
        shell: bash
        run: |
          echo "export ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }} \
          export ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }} \
          export ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> "$GITHUB_OUTPUT"

      - name: Terraform initialization for Azure
        if: ${{ inputs.cloud-provider == 'azure' }}
        uses: ./.github/actions/azure-actions
        with:
          terraform_module: ${{ inputs.module }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}

      - name: AWS login and Terraform initialization
        if: ${{ inputs.cloud-provider == 'aws' }}
        uses: ./.github/actions/aws-actions
        with:
          terraform_module: ${{ inputs.module }}
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          default_region: "eu-central-1"
          arn_role: ${{ secrets.AWS_ARN_ROLE }}

      - name: Terraform plan
        run: |
          if [ "${{ inputs.cloud-provider }}" == "azure" ]; then
            terraform plan -var subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }} -out .planfile
          else
            terraform plan -out .planfile
          fi
        working-directory: ${{ inputs.cloud-provider }}/${{ inputs.module }}
      
      - name: Post PR comment
        uses: borchero/terraform-plan-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          planfile: .planfile
          working-directory: ${{ inputs.cloud-provider }}/${{ inputs.module }}
